apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fullstack-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: QWRtaW4xMjMq  # Admin123*
  POSTGRES_DB: dXN1YXJpb3NkYg==  # usuariosdb
